"""Add returned column to Loan model

Revision ID: ebe697f8632a
Revises: 
Create Date: 2025-01-16 15:11:57.717059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe697f8632a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.Boolean(), nullable=True))
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('SHORT', 'MEDIUM', 'LONG', name='booktype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Enum('SHORT', 'MEDIUM', 'LONG', name='booktype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('returned')

    # ### end Alembic commands ###
